## The input map is generated by tools/bootstrap_input_map.gd. This asserts the
## generated result, so a hand-edit in the editor that drops a binding is caught.
extends TestCase

## Every action the player can press. `melee` is here because it was *not*:
## the sword was bound straight into project.godot, so nothing generated it and
## nothing asserted it, and the only thing standing between the game having a
## sword and not having one was a line in a file no tool owned.
const REQUIRED := [
	&"move_left", &"move_right", &"move_up", &"move_down",
	&"jump", &"shoot", &"melee", &"weapon_prev", &"weapon_next", &"pause",
]


func test_every_gameplay_action_exists() -> void:
	for action in REQUIRED:
		assert_true(InputMap.has_action(action), "missing action %s" % action)


## Slide is down + jump, as in Mega Man 3. If it ever becomes its own binding,
## the feel is wrong and this fails.
func test_slide_is_not_a_separate_action() -> void:
	assert_false(InputMap.has_action(&"slide"),
		"slide must stay as move_down + jump")


func test_actions_have_both_keyboard_and_gamepad_bindings() -> void:
	for action in REQUIRED:
		if not InputMap.has_action(action):
			continue
		var has_key := false
		var has_pad := false
		for event in InputMap.action_get_events(action):
			if event is InputEventKey:
				has_key = true
			elif event is InputEventJoypadButton or event is InputEventJoypadMotion:
				has_pad = true
		assert_true(has_key, "%s has no keyboard binding" % action)
		assert_true(has_pad, "%s has no gamepad binding" % action)


## The generator is meant to be the source of truth for the map (ARCHITECTURE
## section 6 says to re-run it after editing the binding table), so an action
## the game reads and the generator does not know about is an action one
## regeneration away from being someone's puzzle.
func test_the_generator_knows_every_action_the_game_uses() -> void:
	var bindings: Dictionary = load("res://tools/bootstrap_input_map.gd").BINDINGS
	for action in REQUIRED:
		assert_true(bindings.has(action),
			"%s is in the input map but not in bootstrap_input_map.gd" % action)


## Diagonal stick drift on an analogue pad would otherwise trigger slides.
func test_stick_deadzone_is_generous() -> void:
	for action in [&"move_left", &"move_right", &"move_up", &"move_down"]:
		if InputMap.has_action(action):
			assert_true(InputMap.action_get_deadzone(action) >= 0.5,
				"%s deadzone" % action)
