## The input map is generated by tools/bootstrap_input_map.gd. This asserts the
## generated result, so a hand-edit in the editor that drops a binding is caught.
extends TestCase

const REQUIRED := [
	&"move_left", &"move_right", &"move_up", &"move_down",
	&"jump", &"shoot", &"weapon_prev", &"weapon_next", &"pause",
]


func test_every_gameplay_action_exists() -> void:
	for action in REQUIRED:
		assert_true(InputMap.has_action(action), "missing action %s" % action)


## Slide is down + jump, as in Mega Man 3. If it ever becomes its own binding,
## the feel is wrong and this fails.
func test_slide_is_not_a_separate_action() -> void:
	assert_false(InputMap.has_action(&"slide"),
		"slide must stay as move_down + jump")


func test_actions_have_both_keyboard_and_gamepad_bindings() -> void:
	for action in REQUIRED:
		if not InputMap.has_action(action):
			continue
		var has_key := false
		var has_pad := false
		for event in InputMap.action_get_events(action):
			if event is InputEventKey:
				has_key = true
			elif event is InputEventJoypadButton or event is InputEventJoypadMotion:
				has_pad = true
		assert_true(has_key, "%s has no keyboard binding" % action)
		assert_true(has_pad, "%s has no gamepad binding" % action)


## Diagonal stick drift on an analogue pad would otherwise trigger slides.
func test_stick_deadzone_is_generous() -> void:
	for action in [&"move_left", &"move_right", &"move_up", &"move_down"]:
		if InputMap.has_action(action):
			assert_true(InputMap.action_get_deadzone(action) >= 0.5,
				"%s deadzone" % action)
